// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WpfApp27;

#nullable disable

namespace WpfApp27.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20230713170824_dsf")]
    partial class dsf
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("WpfApp27.Model.AdminLoginDetails", b =>
                {
                    b.Property<string>("aUsername")
                        .HasColumnType("TEXT");

                    b.Property<string>("aPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("aUsername");

                    b.ToTable("admintails");
                });

            modelBuilder.Entity("WpfApp27.Model.AdminforumModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Regno")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("admforum");
                });

            modelBuilder.Entity("WpfApp27.Model.Login", b =>
                {
                    b.Property<int>("regno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("regno");

                    b.ToTable("logindetails");
                });

            modelBuilder.Entity("WpfApp27.Model.StudentLoginDetails", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Username");

                    b.ToTable("studetails");
                });

            modelBuilder.Entity("WpfApp27.Model.StudentforumModel", b =>
                {
                    b.Property<int>("regno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("regno");

                    b.ToTable("stdforum");
                });
#pragma warning restore 612, 618
        }
    }
}
